practice-for-ch-rails-music-app-long-practice-main/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resource :session, only: [:create, :destroy, :new]
  resources :bands do 
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index]
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true
  validates :title, uniqueness: {scope: :band_id}
  # validates :live, inclusion: ["true", "false"]
  
  belongs_to :band

end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true, uniqueness: true
  
  has_many :albums

end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6}, allow_nil: true
  attr_reader :password

  before_validation :ensure_session_token

  def generate_unique_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    password_obj = BCrypt::Password.new(self.password_digest)
    password_obj.is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def new
        @album = Album.new
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to bands_url
        else
            # @album = Album.new()
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.new
        render :edit
    end

    def update
        @album = Album.find(params[:id])

        if @album.update
            redirect_to band_url(@album.band_id)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    def show
        @album = Album.find(params[:id])
        render :show
    end

    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to band_url(@album.band_id)
    end

    private
    def album_params
        params.require(:album).permit(:title, :year, :live, :band_id)
    end
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :logout

    def current_user
        @current_user = User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        user.reset_session_token!
        session[:session_token] = user.session_token
    end

    def logout!
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end

end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  def new
    @band = Band.new
    render :new
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    render :edit
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def update
    if @band.update
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def destroy
    @band.destroy
    redirect_to bands_url
  end




  def set_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end



end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        
        if @user 
            login(@user)
            redirect_to user_url(@user)
        else
            # @user = User.new
            flash.now[:errors] = ["Invalid Credentials"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
            login(@user)
            redirect_to users_url(@user)
        else
            flash[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:email, :password)
    end
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<form action="<%= albums_url %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <label for="">
        Title: 
        <input type="text" name="album[title]" value="<%= @album.title %>">
    </label>

    <label for="">
        Year: 
        <input type="text" name="album[year]" value="<%= @album.year %>">
    </label>

    <label for="">
        Live: 
        <input type="text" name="album[live]" value="<%= @album.live %>">
    </label>

    <button type="submit">Edit Band</button>
</form>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/albums/new.html.erb
<h1>Add Album</h1>

<form action="<%=albums_url%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <label for="title">Title
        <input type="text" id="title" name="album[title]">
    </label>

    <label for="year">Year
        <input type="text" id="year" name="album[year]">
    </label>

    <label for="">
        Live: 
        <input type="text" name="album[live]">
    </label>

    <button type="submit">Add Album</button>
</form>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<h3><%= @album.year %></h3>
<%if @album.live%>
    <h3>Live Recording</h3>
    <% else %>
    <h3>Studio Recording</h3>
<% end %>


<form action="<%=album_url(@album)%>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <button type="submit">DELETE Album</button>
</form>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <label for="">
        Name: 
        <input type="text" name="band[name]" value="<%= @band.name %>">
    </label>

    <button type="submit">Edit Band</button>
</form>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/bands/index.html.erb
<h1>BANDS!</h1>
<a href="<%= new_band_url %>">Add a band</a>
<br>
<% @bands.each do |band| %>
    <a href="<%= band_url(band) %>"><%= band.name %></a>
    <br>
<% end %>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/bands/new.html.erb
<h1>Add New Band</h1>

<form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    

    <label for="">
        Name: 
        <input type="text" name="band[name]">
    </label>

    <button type="submit">Add Band</button>
</form>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<a href="<%= new_band_album_url(@band) %>">Add an album</a>

<form action="<%=band_url(@band)%>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <button type="submit">DELETE BAND</button>
</form>


<% @band.albums.each do |album| %>
<a href="<%= album_url(album) %>"><%= album.title %></a>
<% end %>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

    <%if logged_in?%>
      <form action="<%=session_url%>" method="post">
        <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <button type="submit">Log Out</button>

      </form>
        
      <% else %>
          <a href="<%=new_session_url%>">Log In</a>    
          <a href="<%=new_user_url%>">Sign Up</a>
    <% end %>
    

    <%= yield %>
  </body>
</html>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/users/index.html.erb
<h1>Users Index</h1>

<% @users.each do |user| %>
    <a href="<%= user_url(user) %>"><%= user.email %></a>
    <br>
<% end %>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%=  %>
<form action="<%=users_url%>" method="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <label for="email">Email
        <input type="text" id="email" name="user[email]">
    </label>

    <label for="password">Password
        <input type="password" id="password" name="user[password]">
    </label>

    <button type="submit">Sign Up</button>
</form>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/users/show.html.erb
<h1>Welcome <%=@user.email%></h1>

<%= @user.email %>